### ISSUE TITLE
Require more categories

### ISSUE THREAD

**Issue by mtahreemalam** [m-murasovs/amazon-bestsellers-scraper#5]
Hello,
I want to know how can i request more depth in categories as to currently offered as one. I only need the all of the category and subcategory names

**Comment by m-murasovs** [comment]
Hi, thanks for getting in touch! 
Are you familiar with coding? If so, there is commented-out code in the [main.js](https://github.com/m-murasovs/amazon-bestsellers-scraper/issues/5) file  that goes to the third level of subcategory. 

Then, if you only want to scrape the category and subcategory names, you could try and comment out this code:
```
// Scrape items from enqueued pages
if (request.userData.detailPage) {
    await scrapeDetailsPage(page, results);
}
```
, which grabs the items from each page. 

This selector `'ul > ul > ul > li > a` in main.js grabs the category names, so you could try and modify the functions to ignore scraping depth and just keep going.

I hope this helps!
